version: "3.3"

networks:
  proxy:
    external: true

services:
  test-redeploy:
    image: structej/projetos:test-latest
    build: https://github.com/artistrea/teste-gh-action.git#${BRANCH:-production}
    restart: always
    ports:
      - 3000
