name: Redeploy
on:
  push:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request
        env:
        #   URL: "https://deployer-microservice.structej.com"
          URL: "https://jsonplaceholder.typicode.com/posts"
          BODY: '{"action": "build", "name": 1 }'
        run: |
          curl -X POST \
            "$URL"
