name: Redeploy
on:
  push:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request to Microservice
        env:
          URL: "https://deployer-microservice.structej.com"
          BODY: '{"action": "build", "id": 1 }'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Authorization: testando_aa" \
            -d "${BODY}" \
            "${URL}"
